# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Departments
Department.create(id: 1 , name: 'ส่วนอำนวยการและบุคคล' , short: 'อบ.')
Department.create(id: 2 , name: 'ส่วนการเงินและบัญชี' , short: 'กง.')
Department.create(id: 3 , name: 'ส่วนเทคโนลยีสารสนเทศ' , short: 'รส.')
Department.create(id: 4 , name: 'ส่วนทรัพย์สินและพัสดุ' , short: 'ทพ.')
Department.create(id: 5 , name: 'ส่วนบริหารงาน e-Commerce' , short: 'บง.')
Department.create(id: 6 , name: 'ส่วนระบบงานนำจ่าย' , short: 'นจ.')
Department.create(id: 7 , name: 'ส่วนรับฝากและส่งต่อ' , short: 'รต.')
Department.create(id: 8 , name: 'ส่วนตลาดและลูกค้าธุรกิจ' , short: 'ตธ.')
Department.create(id: 9 , name: 'ส่วนควบคุมคุณภาพ' , short: 'คภ.')

# Level
Level.create(id: 1 , name: 'Admin')
Level.create(id: 2 , name: 'หัวหน้าส่วน')
Level.create(id: 3 , name: 'เจ้าหน้าที่ ปข.6')
Level.create(id: 4 , name: 'หัวหน้าที่ทำการไปรษณีย์')
Level.create(id: 5 , name: 'พนักงานไปรษณีย์')

# Position
Position.create(id: 1 , name: 'Admin')
Position.create(id: 2 , name: 'หนส.')
Position.create(id: 3 , name: 'หน.ปณ.')
Position.create(id: 4 , name: 'พนักงาน')
Position.create(id: 5 , name: 'ลูกจ้างประจำ')
Position.create(id: 6 , name: 'ลูกจ้าง')
Position.create(id: 7 , name: 'ผู้รับจ้างทำของ')

# Confidential
Confidential.create(id: 1 , name: 'ปกติ')
Confidential.create(id: 2 , name: 'ด่วน')
Confidential.create(id: 3 , name: 'ด่วนมาก')
Confidential.create(id: 4 , name: 'ด่วนที่สุด')

# Destination
  # mail center
Destination.create(id: 1 , name: 'ศป.นครสวรรค์' , postcode: '60010')
Destination.create(id: 2 , name: 'ศป.พิษณุโลก' , postcode: '65010')

  # Nakhonsawan
Destination.create(id: 3 , name: 'ปจ.นครสวรรค์' , postcode: '60000')
Destination.create(id: 4 , name: 'ปณฝ.สวรรค์วิถี' , postcode: '60001')
Destination.create(id: 5 , name: 'ปณฝ.จิรประวัติ' , postcode: '60002')
Destination.create(id: 6 , name: 'ปณ.หนองบัว' , postcode: '60110')
Destination.create(id: 7 , name: 'ปณ.ชุมแสง' , postcode: '60120')
Destination.create(id: 8 , name: 'ปณ.พยุหะคีรี' , postcode: '60130')
Destination.create(id: 9 , name: 'ปณ.ตาคลี' , postcode: '60140')
Destination.create(id: 10 , name: 'ปณ.ลาดยาว' , postcode: '60150')
Destination.create(id: 11 , name: 'ปณ.ท่าตะโก' , postcode: '60160')
Destination.create(id: 12 , name: 'ปณ.โกรกพระ' , postcode: '60170')
Destination.create(id: 13 , name: 'ปณ.บรรพตพิสัย' , postcode: '60180')
Destination.create(id: 14 , name: 'ปณ.ตากฟ้า' , postcode: '60190')
Destination.create(id: 15 , name: 'ปณ.ช่องแค' , postcode: '60210')
Destination.create(id: 16 , name: 'ปณ.ไพศาลี' , postcode: '60220')
Destination.create(id: 17 , name: 'ปณ.เก้าเลี้ยว' , postcode: '60230')
Destination.create(id: 18 , name: 'ปณ.หนองเบน' , postcode: '60240')
Destination.create(id: 19 , name: 'ปณ.ทับกฤช' , postcode: '60250')
Destination.create(id: 20 , name: 'ปณ.จันเสน' , postcode: '60260')

  # Uthaitanee
Destination.create(id: 21 , name: 'ปจ.อุทัยธานี' , postcode: '61000')
Destination.create(id: 22 , name: 'ปณ.หนองฉาง' , postcode: '61110')
Destination.create(id: 23 , name: 'ปณ.ทัพทัน' , postcode: '61120')
Destination.create(id: 24 , name: 'ปณ.หนองขาหย่าง' , postcode: '61130')
Destination.create(id: 25 , name: 'ปณ.บ้านไร่' , postcode: '61140')
Destination.create(id: 26 , name: 'ปณ.สว่างอารมณ์' , postcode: '61150')
Destination.create(id: 27 , name: 'ปณ.ลานสัก' , postcode: '61160')
Destination.create(id: 28 , name: 'ปณ.เขาบางแกรก' , postcode: '61170')
Destination.create(id: 29 , name: 'ปณ.เมืองการุ้ง' , postcode: '61180')

  # Kampangphet
Destination.create(id: 30 , name: 'ปจ.กำแพงเพชร' , postcode: '62000')
Destination.create(id: 31 , name: 'ปณ.พรานกระต่าย' , postcode: '62110')
Destination.create(id: 32 , name: 'ปณ.คลองขลุง' , postcode: '62120')
Destination.create(id: 33 , name: 'ปณ.ขาณุวรลักษบุรี' , postcode: '62130')
Destination.create(id: 34 , name: 'ปณ.สลกบาตร' , postcode: '62140')
Destination.create(id: 35 , name: 'ปณ.ไทรงาม' , postcode: '62150')
Destination.create(id: 36 , name: 'ปณ.ปากดง' , postcode: '62160')
Destination.create(id: 37 , name: 'ปณ.ลานกระบือ' , postcode: '62170')
Destination.create(id: 38 , name: 'ปณ.คลองลาน' , postcode: '62180')
Destination.create(id: 39 , name: 'ปณ.ทุ่งทราย' , postcode: '62190')
Destination.create(id: 40 , name: 'ปณ.ระหาน' , postcode: '62210')

  # Tak
Destination.create(id: 41 , name: 'ปจ.ตาก' , postcode: '63000')
Destination.create(id: 42 , name: 'ปณ.แม่สอด' , postcode: '63110')
Destination.create(id: 43 , name: 'ปณ.อินทร์คีรี' , postcode: '63120')
Destination.create(id: 44 , name: 'ปณ.บ้านตาก' , postcode: '63130')
Destination.create(id: 45 , name: 'ปณ.สามเงา' , postcode: '63140')
Destination.create(id: 46 , name: 'ปณ.แม่ระมาด' , postcode: '63150')
Destination.create(id: 47 , name: 'ปณ.ท่าสองยาง' , postcode: '63160')
Destination.create(id: 48 , name: 'ปณ.อุ้มผาง' , postcode: '63170')
Destination.create(id: 49 , name: 'ปณ.วังเจ้า' , postcode: '63180')

  # Sukhothai
Destination.create(id: 50 , name: 'ปจ.สุโขทัย' , postcode: '64000')
Destination.create(id: 51 , name: 'ปณ.สวรรคโลก' , postcode: '64110')
Destination.create(id: 52 , name: 'ปณ.ศรีสำโรง' , postcode: '64120')
Destination.create(id: 53 , name: 'ปณ.ศรีสัชนาลัย' , postcode: '64130')
Destination.create(id: 54 , name: 'ปณ.บ้านด่านลานหอย' , postcode: '64140')
Destination.create(id: 55 , name: 'ปณ.ทุ่งเสลี่ยม' , postcode: '64150')
Destination.create(id: 56 , name: 'ปณ.คีรีมาศ' , postcode: '64160')
Destination.create(id: 57 , name: 'ปณ.กงไกรลาศ' , postcode: '64170')
Destination.create(id: 58 , name: 'ปณ.ศรีนคร' , postcode: '64180')
Destination.create(id: 59 , name: 'ปณ.ท่าชัย' , postcode: '64190')
Destination.create(id: 60 , name: 'ปณ.เมืองเก่า' , postcode: '64210')
Destination.create(id: 61 , name: 'ปณ.บ้านสวน' , postcode: '64220')
Destination.create(id: 62 , name: 'ปณ.บ้านใหม่ไชยมงคล' , postcode: '64230')

  # Phitsanulok
Destination.create(id: 63 , name: 'ปจ.พิษณุโลก' , postcode: '65000')
Destination.create(id: 64 , name: 'ปณฝ.อรัญญิก' , postcode: '65001')
Destination.create(id: 65 , name: 'ปณ.บางกระทุ่ม' , postcode: '65110')
Destination.create(id: 66 , name: 'ปณ.นครไทย' , postcode: '65120')
Destination.create(id: 67 , name: 'ปณ.วังทอง' , postcode: '65130')
Destination.create(id: 68 , name: 'ปณ.บางระกำ' , postcode: '65140')
Destination.create(id: 69 , name: 'ปณ.พรหมพิราม' , postcode: '65150')
Destination.create(id: 70 , name: 'ปณ.วัดโบสถ์' , postcode: '65160')
Destination.create(id: 71 , name: 'ปณ.ชาติตระการ' , postcode: '65170')
Destination.create(id: 72 , name: 'ปณ.หนองตม' , postcode: '65180')
Destination.create(id: 73 , name: 'ปณ.เนินมะปราง' , postcode: '65190')
Destination.create(id: 74 , name: 'ปณ.เนินกุ่ม' , postcode: '65210')
Destination.create(id: 75 , name: 'ปณ.แก่งโสภา' , postcode: '65220')
Destination.create(id: 76 , name: 'ปณ.วัดพริก' , postcode: '65230')
Destination.create(id: 77 , name: 'ปณ.ชุมแสงสงคราม' , postcode: '65240')

  # pichit
Destination.create(id: 78 , name: 'ปจ.พิจิตร' , postcode: '66000')
Destination.create(id: 79 , name: 'ปณ.ตะพานหิน' , postcode: '66110')
Destination.create(id: 80 , name: 'ปณ.บางมูลนาก' , postcode: '66120')
Destination.create(id: 81 , name: 'ปณ.โพทะเล' , postcode: '66130')
Destination.create(id: 82 , name: 'ปณ.สามง่าม' , postcode: '66140')
Destination.create(id: 83 , name: 'ปณ.ทับคล้อ' , postcode: '66150')
Destination.create(id: 84 , name: 'ปณ.สากเหล็ก' , postcode: '66160')
Destination.create(id: 85 , name: 'ปณ.หัวดง' , postcode: '66170')
Destination.create(id: 86 , name: 'ปณ.วังทรายพูน' , postcode: '66180')
Destination.create(id: 87 , name: 'ปณ.โพธิ์ประทับช้าง' , postcode: '66190')
Destination.create(id: 88 , name: 'ปณ.วังตะกู' , postcode: '66210')
Destination.create(id: 89 , name: 'ปณ.กำแพงดิน' , postcode: '66220')
Destination.create(id: 90 , name: 'ปณ.เขาทราย' , postcode: '66230')

  # Phetchaboon
Destination.create(id: 91 , name: 'ปจ.เพชรบูรณ์' , postcode: '67000')
Destination.create(id: 92 , name: 'ปณ.หล่มสัก' , postcode: '67110')
Destination.create(id: 93 , name: 'ปณ.หล่มเก่า' , postcode: '67120')
Destination.create(id: 94 , name: 'ปณ.วิเชียรบุรี' , postcode: '67130')
Destination.create(id: 95 , name: 'ปณ.หนองไผ่' , postcode: '67140')
Destination.create(id: 96 , name: 'ปณ.ชนแดน' , postcode: '67150')
Destination.create(id: 97 , name: 'ปณ.บึงสามพัน' , postcode: '67160')
Destination.create(id: 98 , name: 'ปณ.ศรีเทพ' , postcode: '67170')
Destination.create(id: 99 , name: 'ปณ.พุเตย' , postcode: '67180')
Destination.create(id: 100 , name: 'ปณ.ดงขุย' , postcode: '67190')
Destination.create(id: 101 , name: 'ปณ.วังชมภู' , postcode: '67210')
Destination.create(id: 102 , name: 'ปณ.นาเฉลียง' , postcode: '67220')
Destination.create(id: 103 , name: 'ปณ.วังพิกุล' , postcode: '67230')
Destination.create(id: 104 , name: 'ปณ.วังโป่ง' , postcode: '67240')
Destination.create(id: 105 , name: 'ปณ.ท่าพล' , postcode: '67250')
Destination.create(id: 106 , name: 'ปณ.น้ำหนาว' , postcode: '67260')
Destination.create(id: 107 , name: 'ปณ.เขาค้อ' , postcode: '67270')
Destination.create(id: 108 , name: 'ปณ.แคมป์สน' , postcode: '67280')

  # Counter
Destination.create(id: 109 , name: 'คปณ.บิ๊กซีนครสวรรค์' , postcode: '60000')
Destination.create(id: 110 , name: 'คปณ.ชากังราว' , postcode: '62000')
Destination.create(id: 111 , name: 'คปณ.เจริญสุข' , postcode: '62000')
Destination.create(id: 112 , name: 'คปณ.ท่ามะเขือ' , postcode: '62120')
Destination.create(id: 113 , name: 'คปณ.ตลาดริมเมย' , postcode: '63110')
Destination.create(id: 114 , name: 'คปณ.สี่แยกคลองโพธิ์' , postcode: '64000')
Destination.create(id: 115 , name: 'คปณ.สี่แยกอินโดจีน' , postcode: '65000')
Destination.create(id: 116 , name: 'คปณ.บรมไตรโลกนารถ' , postcode: '65000')
Destination.create(id: 117 , name: 'คปณ.มหาวิทยาลัยนเรศวร' , postcode: '65000')
Destination.create(id: 118 , name: 'คปณ.ท่าโพธิ์' , postcode: '65000')
Destination.create(id: 119 , name: 'คปณ.บ้านคลอง' , postcode: '65000')
Destination.create(id: 120 , name: 'คปณ.ราชภัฎเพชรบูรณ์' , postcode: '67000')
Destination.create(id: 121 , name: 'คปณ.สี่แยกพ่อขุนผาเมือง' , postcode: '67110')

  # Departments in reg6
Destination.create(id: 122 , name: 'ส่วนอำนวยการและบุคคล' , postcode: '60000')
Destination.create(id: 123 , name: 'ส่วนการเงินและบัญชี' , postcode: '60000')
Destination.create(id: 124 , name: 'ส่วนเทคโนลยีสารสนเทศ' , postcode: '60000')
Destination.create(id: 125 , name: 'ส่วนทรัพย์สินและพัสดุ' , postcode: '60000')
Destination.create(id: 126 , name: 'ส่วนบริหารงาน e-Commerce' , postcode: '60000')
Destination.create(id: 127 , name: 'ส่วนระบบงานนำจ่าย' , postcode: '60000')
Destination.create(id: 128 , name: 'ส่วนรับฝากและส่งต่อ' , postcode: '60000')
Destination.create(id: 129 , name: 'ส่วนตลาดและลูกค้าธุรกิจ' , postcode: '60000')
Destination.create(id: 130 , name: 'ส่วนควบคุมคุณภาพ' , postcode: '60000')
